// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        return windows;
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyApF6SSapd9KFwCNAOeKfXcWHaOxNsiMBk',
    appId: '1:741105956958:web:b2668bed039a5690965ccf',
    messagingSenderId: '741105956958',
    projectId: 'personal-finance-tracker-e8905',
    authDomain: 'personal-finance-tracker-e8905.firebaseapp.com',
    databaseURL: 'https://personal-finance-tracker-e8905-default-rtdb.asia-southeast1.firebasedatabase.app',
    storageBucket: 'personal-finance-tracker-e8905.firebasestorage.app',
    measurementId: 'G-VHHQVHPH4F',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyD6Id9rFncOEZPVwvZG7FQ1IKl3tlUB-64',
    appId: '1:741105956958:android:2ddcc5ce267a87b5965ccf',
    messagingSenderId: '741105956958',
    projectId: 'personal-finance-tracker-e8905',
    databaseURL: 'https://personal-finance-tracker-e8905-default-rtdb.asia-southeast1.firebasedatabase.app',
    storageBucket: 'personal-finance-tracker-e8905.firebasestorage.app',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyDMr5sg5dbxDUMo9jSqLnFM1bq_PU2yjWw',
    appId: '1:741105956958:ios:411d189978d63fd6965ccf',
    messagingSenderId: '741105956958',
    projectId: 'personal-finance-tracker-e8905',
    databaseURL: 'https://personal-finance-tracker-e8905-default-rtdb.asia-southeast1.firebasedatabase.app',
    storageBucket: 'personal-finance-tracker-e8905.firebasestorage.app',
    iosBundleId: 'com.example.financeTracker',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyDMr5sg5dbxDUMo9jSqLnFM1bq_PU2yjWw',
    appId: '1:741105956958:ios:411d189978d63fd6965ccf',
    messagingSenderId: '741105956958',
    projectId: 'personal-finance-tracker-e8905',
    databaseURL: 'https://personal-finance-tracker-e8905-default-rtdb.asia-southeast1.firebasedatabase.app',
    storageBucket: 'personal-finance-tracker-e8905.firebasestorage.app',
    iosBundleId: 'com.example.financeTracker',
  );

  static const FirebaseOptions windows = FirebaseOptions(
    apiKey: 'AIzaSyApF6SSapd9KFwCNAOeKfXcWHaOxNsiMBk',
    appId: '1:741105956958:web:d44b4a73e9a60c6e965ccf',
    messagingSenderId: '741105956958',
    projectId: 'personal-finance-tracker-e8905',
    authDomain: 'personal-finance-tracker-e8905.firebaseapp.com',
    databaseURL: 'https://personal-finance-tracker-e8905-default-rtdb.asia-southeast1.firebasedatabase.app',
    storageBucket: 'personal-finance-tracker-e8905.firebasestorage.app',
    measurementId: 'G-6YFR7RB92X',
  );

}