import 'dart:io';

import 'package:finance_tracker/models/expense_model.dart';
import 'package:finance_tracker/utils/firebase_service.dart';
import 'package:flutter/material.dart';
import 'package:image_picker/image_picker.dart';

class AddExpenseScreen extends StatefulWidget {
  const AddExpenseScreen({super.key});

  @override
  State<AddExpenseScreen> createState() => _AddExpenseScreenState();
}

class _AddExpenseScreenState extends State<AddExpenseScreen> {
  final TextEditingController _descriptionController = TextEditingController();
  final TextEditingController _amountController = TextEditingController();
  String? _selectedCategory;
  String? _selectedCurrency = 'INR'; // Default to INR, you can expand this
  File? _selectedImage;
  final FirebaseService _firebaseService = FirebaseService();
  bool _isLoading = false; // Added loading state

  void _saveExpense() async {
    if (_descriptionController.text.isEmpty ||
        _amountController.text.isEmpty ||
        _selectedCategory == null ||
        _selectedCurrency == null) {
      ScaffoldMessenger.of(context).showSnackBar(
        const SnackBar(content: Text('Please fill out all fields')),
      );
      return;
    }

    // Create an instance of ExpenseModel
    ExpenseModel expense = ExpenseModel(
      id: '', // ID will be generated by Firestore on add
      amount: double.parse(_amountController.text),
      category: _selectedCategory!,
      description: _descriptionController.text,
      date: DateTime.now(), // Default to current date
      imagePath: _selectedImage?.path, // Optional image path
      currency: _selectedCurrency!,
    );

    setState(() {
      _isLoading = true; // Set loading state
    });

    // Call addExpense with the ExpenseModel
    await _firebaseService.addExpense(expense);

    setState(() {
      _isLoading = false; // Reset loading state
    });

    Navigator.pop(context); // Go back to the previous screen
  }

  Future<void> _pickImage() async {
    final ImagePicker picker = ImagePicker();
    final XFile? pickedImage = await picker.pickImage(
      source: ImageSource.gallery,
      maxWidth: 1024,
      maxHeight: 1024,
      imageQuality: 85,
    );

    if (pickedImage != null) {
      setState(() {
        _selectedImage = File(pickedImage.path);
      });
    }
  }

  @override
  Widget build(BuildContext context) {
    return Scaffold(
      appBar: AppBar(title: const Text('Add Expense')),
      body: Padding(
        padding: const EdgeInsets.all(16.0),
        child: Column(
          children: [
            TextField(
              controller: _descriptionController,
              decoration: const InputDecoration(labelText: 'Description'),
            ),
            TextField(
              controller: _amountController,
              decoration: const InputDecoration(labelText: 'Amount'),
              keyboardType: TextInputType.number,
            ),
            StreamBuilder<List<String>>(
              stream: _firebaseService.getCategories(),
              builder: (context, snapshot) {
                if (snapshot.connectionState == ConnectionState.waiting) {
                  return const CircularProgressIndicator(); // While loading
                } else if (snapshot.hasError) {
                  return Text('Error: ${snapshot.error}'); // If error occurs
                } else if (!snapshot.hasData || snapshot.data!.isEmpty) {
                  return const Text('No categories available'); // When no data
                }

                return DropdownButton<String>(
                  value: _selectedCategory,
                  hint: const Text('Select Category'),
                  items: snapshot.data!.map((category) {
                    return DropdownMenuItem(
                      value: category,
                      child: Text(category),
                    );
                  }).toList(),
                  onChanged: (value) {
                    setState(() {
                      _selectedCategory = value;
                    });
                  },
                );
              },
            ),
            const SizedBox(height: 16),
            DropdownButton<String>(
              value: _selectedCurrency,
              onChanged: (value) {
                setState(() {
                  _selectedCurrency = value;
                });
              },
              items: ['USD', 'EUR', 'INR', 'GBP'].map((currency) {
                return DropdownMenuItem<String>(
                  value: currency,
                  child: Text(currency),
                );
              }).toList(),
              hint: const Text('Select Currency'),
            ),
            const SizedBox(height: 16),
            _selectedImage == null
                ? ElevatedButton(
                    onPressed: _pickImage,
                    child: const Text('Pick Image'),
                  )
                : Image.file(
                    _selectedImage!,
                    height: 150,
                    width: 150,
                    fit: BoxFit.cover,
                  ),
            const SizedBox(height: 16),
            _isLoading
                ? const CircularProgressIndicator()
                : ElevatedButton(
                    onPressed: _saveExpense,
                    child: const Text('Save Expense'),
                  ),
          ],
        ),
      ),
    );
  }
}
